name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::586794466344:role/GitHubActionsRole
        aws-region: us-east-1

    - name: Sync to S3
      run: |
        aws s3 sync . s3://ryanresume --no-progress --no-follow-symlinks --size-only